# Generated by Django 4.1.5 on 2023-02-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_post_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, default='static/images/avatar.jpg', null=True, upload_to='posts'),
        ),
    ]
